# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    # Note: Dependabot can't parse most of build.gradle.kts because of IJ Platform's DSL
    groups:
      gradle:
        patterns:
          - "*"
